import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./lib/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: { default: "Rk Blog", template: "%s | RK Blog" },
  description: "Generated by Rahul",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="lg:p-24">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
